#
# DISCLAIMER: THIS IS FOR DEVELOPMENT PURPOSES ONLY AND NOT SUITABLE FOR PRODUCTION.
#
version: '3'

services:
  db:
    # NOTE: No persistence storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgis/postgis:14-3.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=openarchiefbeheer
      - POSTGRES_PASSWORD=openarchiefbeheer
    networks:
      - open-archiefbeheer-dev

  redis:
    # NOTE: No persistence storage configured.
    image: redis:6
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - open-archiefbeheer-dev

  web:
    image: maykinmedia/open-archiefbeheer:latest
    environment:
      - ALLOWED_HOSTS=localhost
      - DJANGO_SETTINGS_MODULE=openarchiefbeheer.conf.docker
      - SECRET_KEY=${SECRET_KEY:-django-insecure-!bkx+tx18&lvp(@_9)9ut(y(keqho*zhz1&^sqqgq9*i=__w(}
      - DB_NAME=openarchiefbeheer
      - DB_USER=openarchiefbeheer
      - DB_HOST=db
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - CORS_ALLOWED_ORIGINS=http://localhost:9000,http://localhost:8080
      - CSRF_TRUSTED_ORIGINS=http://localhost:9000,http://localhost:8080
      - CSRF_COOKIE_SAMESITE=none
      - CSRF_COOKIE_SECURE=False
      - SESSION_COOKIE_SAMESITE=none
      - SESSION_COOKIE_SECURE=False
      - TWO_FACTOR_FORCE_OTP_ADMIN=False
      - TWO_FACTOR_PATCH_ADMIN=False
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    networks:
      - open-archiefbeheer-dev

  nginx:
    image: nginx
    volumes:
      - ./docker-nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '9000:80'
    depends_on:
      - web
    networks:
      - open-archiefbeheer-dev

networks:
  open-archiefbeheer-dev:
    name: open-archiefbeheer-dev
