# Generated by Django 4.2.14 on 2024-07-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_emailconfig_body_last_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfig",
            name="body_error_during_deletion",
            field=models.TextField(
                blank=True,
                help_text="Body of the email that will be sent to the record manager when an error happened during deletion.",
                verbose_name="body error during deletion",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="subject_error_during_deletion",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email that will be sent to the record manager when an error happened during deletion.",
                max_length=250,
                verbose_name="subject error during deletion",
            ),
        ),
    ]
