# Generated by Django 4.2.15 on 2024-09-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_emailconfig_body_successful_deletion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_last_review",
        ),
        migrations.RemoveField(
            model_name="emailconfig",
            name="subject_last_review",
        ),
    ]
