# Generated by Django 4.2.16 on 2024-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_remove_emailconfig_body_last_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfig",
            name="body_co_review_request",
            field=models.TextField(
                blank=True,
                help_text="Body of the email that will be sent to the co-reviewer(s) when the main reviewer assigns them.",
                verbose_name="body co-review request",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="subject_co_review_request",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email that will be sent to the co-reviewer(s) when the main reviewer assigns them.",
                max_length=250,
                verbose_name="subject co-review request",
            ),
        ),
    ]
