# Generated by Django 4.2.17 on 2025-01-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_emailconfig_body_co_review_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_changes_requested",
        ),
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_co_review_request",
        ),
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_error_during_deletion",
        ),
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_positive_review",
        ),
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_review_reminder",
        ),
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_review_required",
        ),
        migrations.RemoveField(
            model_name="emailconfig",
            name="body_successful_deletion",
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_changes_requested_html",
            field=models.TextField(
                blank=True,
                help_text="HTML body of the email that will be sent to the record manager when a reviewer has requested changes to a destruction list.",
                verbose_name="html body changes requested",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_changes_requested_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text body of the email that will be sent to the record manager when a reviewer has requested changes to a destruction list.",
                verbose_name="text body changes requested",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_co_review_request_html",
            field=models.TextField(
                blank=True,
                help_text="HTML body of the email that will be sent to the co-reviewer(s) when the main reviewer assigns them.",
                verbose_name="HTML body co-review request",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_co_review_request_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text body of the email that will be sent to the co-reviewer(s) when the main reviewer assigns them.",
                verbose_name="text body co-review request",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_error_during_deletion_html",
            field=models.TextField(
                blank=True,
                help_text="HTML body of the email that will be sent to the record manager when an error happened during deletion.",
                verbose_name="HTML body error during deletion",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_error_during_deletion_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text body of the email that will be sent to the record manager when an error happened during deletion.",
                verbose_name="text body error during deletion",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_positive_review_html",
            field=models.TextField(
                blank=True,
                help_text="HTML body of the email that will be sent to the record manager when a reviewer has approved a destruction list.",
                verbose_name="html body positive review",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_positive_review_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text body of the email that will be sent to the record manager when a reviewer has approved a destruction list.",
                verbose_name="text body positive review",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_review_reminder_html",
            field=models.TextField(
                blank=True,
                help_text="HTML body of the email that will be sent to a reviewer after a configured period of time if they still haven't reviewed a destruction list.",
                verbose_name="html body review reminder",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_review_reminder_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text body of the email that will be sent to a reviewer after a configured period of time if they still haven't reviewed a destruction list.",
                verbose_name="text body review reminder",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_review_required_html",
            field=models.TextField(
                blank=True,
                help_text="HTML body of the email that will be sent to a reviewer when there is a destruction list ready to be reviewed.",
                verbose_name="html body review required",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_review_required_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text body of the email that will be sent to a reviewer when there is a destruction list ready to be reviewed.",
                verbose_name="text body review required",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_successful_deletion_html",
            field=models.TextField(
                blank=True,
                help_text="HTML body of the email that will be sent to all the assignees when a list is successfully deleted.",
                verbose_name="HTML body successful deletion",
            ),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="body_successful_deletion_text",
            field=models.TextField(
                blank=True,
                help_text="Text body of the email that will be sent to all the assignees when a list is successfully deleted.",
                verbose_name="text body successful deletion",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="subject_changes_requested",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email that will be sent to the record manager when a reviewer has requested changes to a destruction list.",
                max_length=250,
                verbose_name="subject changes requested",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="subject_review_reminder",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email that will be sent to a reviewer after a configured period of time if they still haven't reviewed a destruction list.",
                max_length=250,
                verbose_name="subject review reminder",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="subject_review_required",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email that will be sent to a reviewer when there is a destruction list ready to be reviewed.",
                max_length=250,
                verbose_name="subject review required",
            ),
        ),
    ]
