# Generated by Django 5.2.17 on 2026-09-18 09:07

from django.db import migrations, models
from django.db.models.fields import NOT_PROVIDED


def add_defaults_to_existing_config(apps, _):
    EmailConfig = apps.get_model("emails", "EmailConfig")
    config, _ = EmailConfig.objects.get_or_create()

    updated_fields = []
    for field in config._meta.get_fields():
        # If the field already has a value or a default is not provided -> do nothing
        if getattr(config, field.name) or field.default == NOT_PROVIDED:
            continue

        setattr(config, field.name, field.default)
        updated_fields.append(field.name)

    if updated_fields:
        config.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_remove_emailconfig_body_changes_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='body_changes_requested_html',
            field=models.TextField(blank=True, default='Beste {{ user_name }},\r\n\r\nEr is een voorstel tot aanpassing van uw vernietigingslijst {{ list_name }}. U kunt de lijst en de voorgestelde wijziging <a href="{% destruction_list_link list_name \'process-review\' %}">hier</a> bekijken en af te handelen.', help_text='HTML body of the email that will be sent to the record manager when a reviewer has requested changes to a destruction list.', verbose_name='html body changes requested'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_changes_requested_text',
            field=models.TextField(blank=True, default="Beste {{ user_name }},\r\n\r\nEr is een voorstel tot aanpassing van uw vernietigingslijst {{ list_name }}. U kunt de lijst en de voorgestelde wijziging hier {% destruction_list_link list_name 'process-review' %} bekijken en af te handelen.", help_text='Plain text body of the email that will be sent to the record manager when a reviewer has requested changes to a destruction list.', verbose_name='text body changes requested'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_error_during_deletion_html',
            field=models.TextField(blank=True, default='Beste {{ user_name }},\r\n\r\nEr is een fout opgetreden tijdens het vernietigen van vernietigingslijst {{ list_name }}. Probeer het opnieuw of neem contact op met de IT afdeling.', help_text='HTML body of the email that will be sent to the record manager when an error happened during deletion.', verbose_name='HTML body error during deletion'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_error_during_deletion_text',
            field=models.TextField(blank=True, default='Beste {{ user_name }},\r\n\r\nEr is een fout opgetreden tijdens het vernietigen van vernietigingslijst {{ list_name }}. Probeer het opnieuw of neem contact op met de IT afdeling.', help_text='Plain text body of the email that will be sent to the record manager when an error happened during deletion.', verbose_name='text body error during deletion'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_positive_review_html',
            field=models.TextField(blank=True, default='Beste {{ user_name }}, \r\n\r\nReviewer {{ reviewer }} heeft de Vernietigingslijst {{ list_name }} goedgekeurd. De lijst wacht nu op uw actie. U kunt <a href="{% destruction_list_link list_name \'edit\' %}">hier</a> de lijst bekijken.', help_text='HTML body of the email that will be sent to the record manager when a reviewer has approved a destruction list.', verbose_name='html body positive review'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_positive_review_text',
            field=models.TextField(blank=True, default="Beste {{ user_name }}, \r\n\r\nReviewer {{ reviewer }} heeft de Vernietigingslijst {{ list_name }} goedgekeurd. De lijst wacht nu op uw actie. U kunt hier {% destruction_list_link list_name 'edit' %} de lijst bekijken.", help_text='Plain text body of the email that will be sent to the record manager when a reviewer has approved a destruction list.', verbose_name='text body positive review'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_review_reminder_html',
            field=models.TextField(blank=True, default='Beste {{ user_name }}, \r\n\r\nU heeft kortgeleden een notificatie ontvangen over de Vernietigingslijst die wacht op uw goedkeuring. \r\n\r\nWij zien dat u nog niet geregeerd heeft, wilt u zo spoedig mogelijk op de Vernietigingslijst reageren.', help_text="HTML body of the email that will be sent to a reviewer after a configured period of time if they still haven't reviewed a destruction list.", verbose_name='html body review reminder'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_review_reminder_text',
            field=models.TextField(blank=True, default='Beste {{ user_name }}, \r\n\r\nU heeft kortgeleden een notificatie ontvangen over de Vernietigingslijst die wacht op uw goedkeuring. \r\n\r\nWij zien dat u nog niet geregeerd heeft, wilt u zo spoedig mogelijk op de Vernietigingslijst reageren.', help_text="Plain text body of the email that will be sent to a reviewer after a configured period of time if they still haven't reviewed a destruction list.", verbose_name='text body review reminder'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_review_required_html',
            field=models.TextField(blank=True, default='Beste {{ user_name }},\r\n\r\nUw accordering van een vernietigingslijst wordt gevraagd. U kunt <a href="{% destruction_list_link list_name \'review\' %}">hier</a> de lijst bekijken om te controleren of de zaken op de lijst daadwerkelijk vernietigd kunnen worden.', help_text='HTML body of the email that will be sent to a reviewer when there is a destruction list ready to be reviewed.', verbose_name='html body review required'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_review_required_text',
            field=models.TextField(blank=True, default="Beste {{ user_name }},\r\n\r\nUw accordering van een vernietigingslijst wordt gevraagd. U kunt hier {% destruction_list_link list_name 'review' %} de lijst bekijken om te controleren of de zaken op de lijst daadwerkelijk vernietigd kunnen worden.", help_text='Plain text body of the email that will be sent to a reviewer when there is a destruction list ready to be reviewed.', verbose_name='text body review required'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_successful_deletion_html',
            field=models.TextField(blank=True, default='Beste,\r\n\r\nLijst {{ list_name }} is succesvol verwerkt. Alle zaken en gerelateerde objecten zijn vernietigd.', help_text='HTML body of the email that will be sent to all the assignees when a list is successfully deleted.', verbose_name='HTML body successful deletion'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='body_successful_deletion_text',
            field=models.TextField(blank=True, default='Beste,\r\n\r\nLijst {{ list_name }} is succesvol verwerkt. Alle zaken en gerelateerde objecten zijn vernietigd.', help_text='Text body of the email that will be sent to all the assignees when a list is successfully deleted.', verbose_name='text body successful deletion'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='subject_changes_requested',
            field=models.CharField(blank=True, default='Voorstel voor wijziging van uw vernietigingslijst', help_text='Subject of the email that will be sent to the record manager when a reviewer has requested changes to a destruction list.', max_length=250, verbose_name='subject changes requested'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='subject_error_during_deletion',
            field=models.CharField(blank=True, default='Fout tijdens vernietiging', help_text='Subject of the email that will be sent to the record manager when an error happened during deletion.', max_length=250, verbose_name='subject error during deletion'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='subject_positive_review',
            field=models.CharField(blank=True, default='Goedkeuring vernietigingslijst', help_text='Subject of the email that will be sent to the record manager when a reviewer has approved a destruction list.', max_length=250, verbose_name='subject positive review'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='subject_review_reminder',
            field=models.CharField(blank=True, default='Uw accordering van een vernietigingslijst wordt gevraagd (herinnering)', help_text="Subject of the email that will be sent to a reviewer after a configured period of time if they still haven't reviewed a destruction list.", max_length=250, verbose_name='subject review reminder'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='subject_review_required',
            field=models.CharField(blank=True, default='Uw accordering van een vernietigingslijst wordt gevraagd', help_text='Subject of the email that will be sent to a reviewer when there is a destruction list ready to be reviewed.', max_length=250, verbose_name='subject review required'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='subject_successful_deletion',
            field=models.CharField(blank=True, default='Lijst succesvol verwerkt', help_text='Subject of the email that will be sent to all the assignees when a list is successfully deleted.', max_length=250, verbose_name='subject successful deletion'),
        ),
        migrations.RunPython(
            add_defaults_to_existing_config, migrations.RunPython.noop,
        )
    ]
