# Generated by Django 5.2.17 on 2026-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_alter_emailconfig_field_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='enable_email_notifications',
            field=models.BooleanField(default=True, help_text='Whether to enable e-mail notifications.', verbose_name='enable e-mail notifications'),
        ),
    ]
