# Generated by Django 4.2.11 on 2024-04-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the role",
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "can_start_destruction",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether a user can create a list of cases to be deleted.",
                        verbose_name="can start destruction",
                    ),
                ),
                (
                    "can_review_destruction",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether a user can review a list of cases to be deleted. They can approve it, reject it or provide feedback.",
                        verbose_name="can review destruction",
                    ),
                ),
                (
                    "can_view_case_details",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether a user can view the contents of cases in a lists.",
                        verbose_name="can view case details",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.role",
                verbose_name="role",
            ),
        ),
    ]
