# Generated by Django 4.2.15 on 2024-09-30 11:56

from django.db import migrations

PERMISSIONS = {
    "can_start_destruction": "Can start destruction",
    "can_review_destruction": "Can review destruction",
    "can_review_final_list": "Can review final list",
}

GROUPS = {
    "Record Manager": [
        "can_start_destruction",
    ],
    "Reviewer": [
        "can_review_destruction",
    ],
    "Archivist": [
        "can_review_final_list",
    ],
    "Administrator": [
        "can_start_destruction",
        "can_review_destruction",
        "can_review_final_list",
    ],
}


def create_groups_permissions(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.get_for_model(User)
    for code_name, name in PERMISSIONS.items():
        Permission.objects.get_or_create(
            codename=code_name, name=name, content_type=content_type
        )

    for group_name, permission_codenames in GROUPS.items():
        group, _ = Group.objects.get_or_create(name=group_name)

        for codename in permission_codenames:
            permission = Permission.objects.get(codename=codename)
            group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_can_review_final_list"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_groups_permissions, migrations.RunPython.noop),
    ]
