# Generated by Django 4.2.15 on 2024-09-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_users_to_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
