# Generated by Django 4.2.15 on 2024-10-04 14:35

from django.db import migrations


def create_superuser_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.get_or_create(name="Superuser")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_role_delete_role"),
    ]

    operations = [
        migrations.RunPython(create_superuser_group, migrations.RunPython.noop),
    ]
