# Generated by Django 4.2.18 on 2025-03-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_co_reviewer_permission_to_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("first_name", "last_name"),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
