# Generated by Django 4.2.20 on 2025-04-22 14:17

from django.db import migrations


def add_can_configure_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    User = apps.get_model("accounts", "User")
    ContentType = apps.get_model("contenttypes", "ContentType")

    can_configure_application, _ = Permission.objects.get_or_create(
        codename="can_configure_application",
        name="Can configure application",
        content_type=ContentType.objects.get_for_model(User),
    )

    admin_group, _ = Group.objects.get_or_create(name="Administrator")
    admin_group.permissions.add(can_configure_application)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_options"),
    ]

    operations = [
        migrations.RunPython(add_can_configure_permission, migrations.RunPython.noop)
    ]
