# Generated by Django 4.2.11 on 2024-05-07 14:07

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zaak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True, verbose_name="UUID")),
                ("url", models.URLField(max_length=1000, verbose_name="URL")),
                (
                    "rollen",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            blank=True, max_length=1000, verbose_name="rollen"
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="status"
                    ),
                ),
                ("zaaktype", models.URLField(max_length=1000, verbose_name="zaaktype")),
                (
                    "deelzaken",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            blank=True, max_length=1000, verbose_name="deelzaken"
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "einddatum",
                    models.DateField(blank=True, null=True, verbose_name="einddatum"),
                ),
                (
                    "hoofdzaak",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="hoofdzaak"
                    ),
                ),
                (
                    "kenmerken",
                    models.JSONField(blank=True, null=True, verbose_name="kenmerken"),
                ),
                (
                    "resultaat",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="resultaat"
                    ),
                ),
                ("startdatum", models.DateField(verbose_name="startdatum")),
                (
                    "verlenging",
                    models.JSONField(blank=True, null=True, verbose_name="verlenging"),
                ),
                (
                    "opschorting",
                    models.JSONField(blank=True, null=True, verbose_name="opschorting"),
                ),
                (
                    "toelichting",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="toelichting"
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="omschrijving"
                    ),
                ),
                (
                    "zaakobjecten",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            blank=True, max_length=1000, verbose_name="zaakobjecten"
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "archiefstatus",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="archiefstatus"
                    ),
                ),
                (
                    "eigenschappen",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            blank=True, max_length=1000, verbose_name="eigenschappen"
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="identificatie"
                    ),
                ),
                (
                    "processobject",
                    models.JSONField(
                        blank=True, null=True, verbose_name="processobject"
                    ),
                ),
                (
                    "zaakgeometrie",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326, verbose_name="zaakgeometrie"
                    ),
                ),
                (
                    "bronorganisatie",
                    models.CharField(max_length=9, verbose_name="bronorganisatie"),
                ),
                (
                    "publicatiedatum",
                    models.DateField(
                        blank=True, null=True, verbose_name="publicatiedatum"
                    ),
                ),
                (
                    "archiefnominatie",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="archiefnominatie"
                    ),
                ),
                (
                    "einddatum_gepland",
                    models.DateField(
                        blank=True, null=True, verbose_name="einddatum_gepland"
                    ),
                ),
                (
                    "registratiedatum",
                    models.DateField(
                        blank=True, null=True, verbose_name="registratiedatum"
                    ),
                ),
                (
                    "archiefactiedatum",
                    models.DateField(
                        blank=True, null=True, verbose_name="archiefactiedatum"
                    ),
                ),
                (
                    "processobjectaard",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="processobjectaard"
                    ),
                ),
                (
                    "betalingsindicatie",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="betalingsindicatie"
                    ),
                ),
                (
                    "communicatiekanaal",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="communicatiekanaal",
                    ),
                ),
                (
                    "laatste_betaaldatum",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="laatste betaaldatum"
                    ),
                ),
                (
                    "producten_of_diensten",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            blank=True,
                            max_length=1000,
                            verbose_name="producten of diensten",
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "selectielijstklasse",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="selectielijstklasse",
                    ),
                ),
                (
                    "relevante_andere_zaken",
                    models.JSONField(
                        blank=True, null=True, verbose_name="relevante andere zaken"
                    ),
                ),
                (
                    "zaakinformatieobjecten",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            blank=True, max_length=1000, verbose_name="zaaktype"
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "startdatum_bewaartermijn",
                    models.DateField(
                        blank=True, null=True, verbose_name="startdatum bewaartermijn"
                    ),
                ),
                (
                    "betalingsindicatie_weergave",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="betalingsindicatie weergave",
                    ),
                ),
                (
                    "opdrachtgevende_organisatie",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        verbose_name="opdrachtgevende organisatie",
                    ),
                ),
                (
                    "vertrouwelijkheidaanduiding",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="vertrouwelijkheidaanduiding",
                    ),
                ),
                (
                    "uiterlijke_einddatum_afdoening",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="uiterlijke einddatum afdoening",
                    ),
                ),
                (
                    "verantwoordelijke_organisatie",
                    models.CharField(
                        max_length=9, verbose_name="verantwoordelijke organisatie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaak",
                "verbose_name_plural": "Zaken",
            },
        ),
    ]
