# Generated by Django 4.2.11 on 2024-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0003_zaak__expand_alter_zaak_resultaat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaak",
            name="archiefnominatie",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="archiefnominatie"
            ),
        ),
    ]
