# Generated by Django 4.2.16 on 2024-10-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SelectionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key to access this selection. It should be the uuid of a destruction list and an action name.",
                        max_length=250,
                        verbose_name="key",
                    ),
                ),
                (
                    "zaak_url",
                    models.URLField(
                        help_text="The url of a zaak in the list.",
                        max_length=1000,
                        verbose_name="zaak url",
                    ),
                ),
                (
                    "selection_data",
                    models.JSONField(
                        default=dict,
                        help_text="Data about this item in the selection",
                        verbose_name="selection data",
                    ),
                ),
            ],
            options={
                "verbose_name": "selection item",
                "verbose_name_plural": "selection items",
            },
        ),
    ]
