# Generated by Django 4.2.11 on 2024-07-12 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zaken", "0004_alter_zaak_archiefnominatie"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZaakSelectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected", models.BooleanField()),
                ("detail", models.JSONField(blank=True, null=True)),
                (
                    "zaak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zaken.zaak"
                    ),
                ),
                (
                    "zaak_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="selection.zaakselection",
                    ),
                ),
            ],
        ),
    ]
