# Generated by Django 4.2.16 on 2024-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllSelectedToggle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key to access this selection. ",
                        max_length=250,
                        verbose_name="key",
                    ),
                ),
                (
                    "all_selected",
                    models.BooleanField(
                        help_text="Toggle to set all the items in the selection to 'selected'.",
                        verbose_name="all selected",
                        default=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "all selected toggle",
                "verbose_name_plural": "all selected toggles",
            },
        ),
    ]
