# Generated by Django 4.2.11 on 2024-05-01 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DestructionList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="name"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "end",
                    models.DateTimeField(
                        blank=True,
                        help_text="The timestamp at which all the cases in the list have been deleted.",
                        null=True,
                        verbose_name="end",
                    ),
                ),
                (
                    "contains_sensitive_info",
                    models.BooleanField(
                        default=True,
                        help_text="Specify whether this destruction list contains privacy sensitive data. If set to true, the report of destruction will NOT contain case descriptions or the remarks by the reviewers.",
                        verbose_name="contains sensitive information",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "in progress"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                        ],
                        default="in_progress",
                        max_length=80,
                        verbose_name="status",
                    ),
                ),
                (
                    "zaak_destruction_report_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL of the case containing the destruction report for this destruction list.",
                        verbose_name="zaak destruction report URL",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Currently assigned user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assignee",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Creator of destruction list.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "destruction list",
                "verbose_name_plural": "destruction lists",
            },
        ),
        migrations.CreateModel(
            name="DestructionListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaak",
                    models.URLField(
                        db_index=True,
                        help_text="URL-reference to the ZAAK (in Zaken API), which is planned to be destroyed.",
                        verbose_name="zaak",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "suggested for destruction"),
                            (
                                "removed",
                                "removed from the destruction list during review",
                            ),
                            ("processing", "is currently being destroyed"),
                            ("destroyed", "successfully destroyed"),
                            ("failed", "destruction did not succeed"),
                        ],
                        default="suggested",
                        max_length=80,
                        verbose_name="status",
                    ),
                ),
                (
                    "extra_zaak_data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional information of the zaak",
                        null=True,
                        verbose_name="extra zaak data",
                    ),
                ),
                (
                    "destruction_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="destruction.destructionlist",
                        verbose_name="destruction list",
                    ),
                ),
            ],
            options={
                "verbose_name": "destruction list item",
                "verbose_name_plural": "destruction list items",
                "unique_together": {("destruction_list", "zaak")},
            },
        ),
    ]
