# Generated by Django 4.2.11 on 2024-05-01 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("destruction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestructionListAssignee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "assigned_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="assigned on"
                    ),
                ),
                (
                    "destruction_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignees",
                        to="destruction.destructionlist",
                        verbose_name="destruction list",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user assigned to the destruction list.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "destruction list assignee",
                "verbose_name_plural": "destruction list assignees",
                "ordering": ("order",),
                "abstract": False,
                "unique_together": {("destruction_list", "user")},
            },
        ),
    ]
