# Generated by Django 4.2.11 on 2024-06-06 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0003_destructionlist_status_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlist",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name="uuid"),
        ),
    ]
