# Generated by Django 4.2.11 on 2024-06-06 09:17

from django.db import migrations
import uuid


def generate_uuid(apps, schema_editor):
    DestructionList = apps.get_model("destruction", "DestructionList")
    for destruction_list in DestructionList.objects.all():
        destruction_list.uuid = uuid.uuid4()
        destruction_list.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0004_destructionlist_uuid"),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
    ]
