# Generated by Django 4.2.11 on 2024-06-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("destruction", "0006_remove_uuid_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestructionListReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("accepted", "accepted"), ("rejected", "rejected")],
                        max_length=80,
                        verbose_name="decision",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "list_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Feedback about the destruction list as a whole.",
                        max_length=2000,
                        verbose_name="list feedback",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created the review.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "destruction_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="destruction.destructionlist",
                        verbose_name="destruction list",
                    ),
                ),
            ],
            options={
                "verbose_name": "destruction list review",
                "verbose_name_plural": "destruction list reviews",
            },
        ),
        migrations.CreateModel(
            name="DestructionListItemReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=False,
                        help_text="If 'other' was selected in the field 'requested change', feedback about what should be done with the case can be provided here.",
                        max_length=2000,
                        verbose_name="feedback",
                    ),
                ),
                (
                    "destruction_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_reviews",
                        to="destruction.destructionlist",
                        verbose_name="destruction list",
                    ),
                ),
                (
                    "destruction_list_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="destruction.destructionlistitem",
                        verbose_name="destruction list item",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_reviews",
                        to="destruction.destructionlistreview",
                        verbose_name="review",
                    ),
                ),
            ],
            options={
                "verbose_name": "destruction list item review",
                "verbose_name_plural": "destruction list item reviews",
            },
        ),
    ]
