# Generated by Django 4.2.11 on 2024-06-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0007_destructionlistreview_destructionlistitemreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistassignee",
            name="role",
            field=models.CharField(
                choices=[("reviewer", "Reviewer"), ("author", "Author")],
                default="reviewer",
                max_length=80,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="destructionlist",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready_to_review", "ready to review"),
                    ("changes_requested", "changes requested"),
                    ("ready_to_delete", "ready to delete"),
                    ("deleted", "deleted"),
                ],
                default="ready_to_review",
                max_length=80,
                verbose_name="status",
            ),
        ),
    ]
