# Generated by Django 4.2.11 on 2024-06-20 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0008_destructionlistassignee_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="The response of the author of the destruction list to a review.",
                        max_length=2000,
                        verbose_name="comment",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="destruction.destructionlistreview",
                        verbose_name="review",
                    ),
                ),
            ],
            options={
                "verbose_name": "review response",
                "verbose_name_plural": "review responses",
            },
        ),
        migrations.CreateModel(
            name="ReviewItemResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_item",
                    models.CharField(
                        choices=[("keep", "keep"), ("remove", "remove")],
                        max_length=80,
                        verbose_name="action item",
                    ),
                ),
                (
                    "action_zaak",
                    models.JSONField(
                        blank=True,
                        help_text="Fields that should be changed on the case.",
                        null=True,
                        verbose_name="action case",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="The response of the author of the destruction list to feedback of the reviewer on a specific case.",
                        max_length=2000,
                        verbose_name="comment",
                    ),
                ),
                (
                    "review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_responses",
                        to="destruction.destructionlistitemreview",
                        verbose_name="review item",
                    ),
                ),
            ],
            options={
                "verbose_name": "review item response",
                "verbose_name_plural": "review item responses",
            },
        ),
    ]
