# Generated by Django 4.2.11 on 2024-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0009_reviewresponse_reviewitemresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewitemresponse",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("succeeded", "succeeded"),
                ],
                default="new",
                help_text="Field used to track the status of the changes that should be made to a destruction list item and the corresponding case.",
                max_length=80,
                verbose_name="processing status",
            ),
        ),
        migrations.AddField(
            model_name="reviewresponse",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("succeeded", "succeeded"),
                ],
                default="new",
                help_text="Field used to track the status of the changes that should be made to a destruction list and the cases.",
                max_length=80,
                verbose_name="processing status",
            ),
        ),
        migrations.AlterField(
            model_name="destructionlistitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("suggested", "suggested for destruction"),
                    ("removed", "removed from the destruction list during review"),
                ],
                default="suggested",
                max_length=80,
                verbose_name="status",
            ),
        ),
    ]
