# Generated by Django 4.2.11 on 2024-06-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0010_reviewitemresponse_processing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="role",
            field=models.CharField(
                choices=[
                    ("reviewer", "reviewer"),
                    ("author", "author"),
                    ("archivist", "archivist"),
                ],
                default="reviewer",
                max_length=80,
                verbose_name="role",
            ),
        ),
    ]
