# Generated by Django 4.2.11 on 2024-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0011_alter_destructionlistassignee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlist",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("ready_to_review", "ready to review"),
                    ("changes_requested", "changes requested"),
                    ("internally_reviewed", "internally reviewed"),
                    ("ready_for_archivist", "ready for archivist"),
                    ("ready_to_delete", "ready to delete"),
                    ("deleted", "deleted"),
                ],
                default="new",
                max_length=80,
                verbose_name="status",
            ),
        ),
    ]
