# Generated by Django 4.2.11 on 2024-06-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0012_alter_destructionlist_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlist",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("succeeded", "succeeded"),
                ],
                default="new",
                help_text="Field used to track the status of the deletion of a destruction list.",
                max_length=80,
                verbose_name="processing status",
            ),
        ),
    ]
