# Generated by Django 4.2.14 on 2024-08-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0014_destructionlistitem_internal_results_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destructionlistassignee",
            options={
                "verbose_name": "destruction list assignee",
                "verbose_name_plural": "destruction list assignees",
            },
        ),
        migrations.RemoveField(
            model_name="destructionlistassignee",
            name="order",
        ),
    ]
