# Generated by Django 4.2.15 on 2024-08-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0004_alter_zaak_archiefnominatie"),
        ("destruction", "0017_destructionlistitem_zaak"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="destructionlistitem",
            unique_together={("destruction_list", "zaak")},
        ),
        migrations.RemoveField(
            model_name="destructionlistitem",
            name="zaak_url",
        ),
    ]
