# Generated by Django 4.2.15 on 2024-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0018_alter_destructionlistitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistassignee",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="comment"),
        ),
    ]
