# Generated by Django 4.2.15 on 2024-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0018_alter_destructionlistitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistitem",
            name="_zaak_url",
            field=models.URLField(
                blank=True,
                help_text="Keep a relation to the zaak for when the zaken cached are being re-synced.",
                max_length=1000,
                verbose_name="zaak url",
            ),
        ),
    ]
