# Generated by Django 4.2.15 on 2024-08-22 09:13

from django.db import migrations


def add_zaak_url(apps, schema_editor):
    DestructionListItem = apps.get_model("destruction", "DestructionListItem")

    items = (
        DestructionListItem.objects.filter(_zaak_url="", zaak__isnull=False)
        .select_related("zaak")
        .iterator(chunk_size=1000)
    )
    updated_items = []
    for item in items:
        item._zaak_url = item.zaak.url
        updated_items.append(item)

    DestructionListItem.objects.bulk_update(updated_items, fields=["_zaak_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0019_destructionlistitem__zaak_url"),
    ]

    operations = [
        migrations.RunPython(add_zaak_url, migrations.RunPython.noop),
    ]
