# Generated by Django 4.2.15 on 2024-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0020_auto_20240822_1113"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlist",
            name="planned_destruction_date",
            field=models.DateField(
                blank=True,
                help_text="Date from which this destruction list can be deleted.",
                null=True,
                verbose_name="planned destruction date",
            ),
        ),
    ]
