# Generated by Django 4.2.15 on 2024-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0021_destructionlist_planned_destruction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewitemresponse",
            name="action_zaak_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "selectielijstklasse_and_bewaartermijn",
                        "selectielijstklasse and bewaartermijn",
                    ),
                    ("bewaartermijn", "bewaartermijn"),
                ],
                help_text="What type of change to do on the case. ",
                max_length=80,
                verbose_name="action zaak type",
            ),
        ),
    ]
