# Generated by Django 4.2.16 on 2024-10-09 10:58

from django.db import migrations
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0022_reviewitemresponse_action_zaak_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlist",
            name="destruction_report",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                null=True,
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="destruction_reports/%Y/%m/%d/",
                verbose_name="destruction report",
            ),
        ),
    ]
