# Generated by Django 4.2.16 on 2024-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0024_destructionlist_internal_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlist",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Explanation of the destruction list.",
                max_length=2000,
                verbose_name="comment",
            ),
        ),
    ]
