# Generated by Django 4.2.16 on 2024-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0024_destructionlist_internal_results_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlistassignee",
            name="role",
            field=models.CharField(
                choices=[
                    ("main_reviewer", "main reviewer"),
                    ("co_reviewer", "co-reviewer"),
                    ("author", "author"),
                    ("archivist", "archivist"),
                ],
                default="main_reviewer",
                max_length=80,
                verbose_name="role",
            ),
        ),
    ]
