# Generated by Django 4.2.16 on 2024-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0025_destructionlist_toelichting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destructionlist",
            name="toelichting",
        ),
        migrations.AddField(
            model_name="destructionlist",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Explanation of the destruction list.",
                max_length=2000,
                null=True,
                verbose_name="comment",
            ),
        ),
    ]
