# Generated by Django 4.2.16 on 2024-11-05 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0026_remove_destructionlist_toelichting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destructionlist",
            name="comment",
            field=models.TextField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Explanation of the destruction list.",
                max_length=2000,
                verbose_name="comment",
            ),
            preserve_default=False,
        ),
    ]
