# Generated by Django 4.2.16 on 2024-11-22 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("destruction", "0026_destructionlist_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestructionListCoReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "list_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Feedback about the destruction list as a whole.",
                        max_length=2000,
                        verbose_name="list feedback",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created the review.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_co_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "destruction_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_reviews",
                        to="destruction.destructionlist",
                        verbose_name="destruction list",
                    ),
                ),
            ],
        ),
    ]
