# Generated by Django 4.2.27 on 2025-12-09 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destruction", "0027_destructionlistcoreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionlistitem",
            name="excluded_relations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(
                    blank=True, max_length=1000, verbose_name="excluded_relations"
                ),
                blank=True,
                default=list,
                help_text="URLs of the related resources (Zaak Objecten) that will not be destroyed when destroying the zaak.",
                size=None,
            ),
        ),
    ]
