# Generated by Django 4.2.27 on 2026-01-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destruction', '0028_destructionlistitem_excluded_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDestructionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL to the ZGW resource that was deleted/unlinked or that still needs to be deleted/unlinked.', verbose_name='URL')),
                ('resource_type', models.CharField(help_text="The type of the resource, for example 'enkelvoudiginformatieobject' or 'zaak'.", max_length=255, verbose_name='resource type')),
                ('status', models.CharField(choices=[('deleted', 'Deleted'), ('unlinked', 'Unlinked'), ('to_be_deleted', 'To be deleted')], max_length=80, verbose_name='status')),
                ('metadata', models.JSONField(default=dict, help_text='After deletion/unlinking of this resource, any metadata that is needed for the destruction report is temporarily stored here. ', verbose_name='Metadata')),
                ('item', models.ForeignKey(help_text='Destruction list item whose processing resulted in the deletion/unlinking of this ZGW resource.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='destruction.destructionlistitem', verbose_name='destruction list item')),
            ],
            options={
                'verbose_name': 'Resource destruction result',
                'verbose_name_plural': 'Resource destruction results',
            },
        ),
        migrations.CreateModel(
            name='ResourceCreationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL to the ZGW resource that was created.', verbose_name='URL')),
                ('resource_type', models.CharField(help_text="The type of the ZGW resource, for example 'resultaat' or 'zaak'.", max_length=255, verbose_name='resource type')),
                ('destruction_list', models.ForeignKey(help_text='Destruction list whose processing resulted in the creation of this ZGW resource.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='destruction.destructionlist', verbose_name='destruction list')),
            ],
            options={
                'verbose_name': 'Resource creation result',
                'verbose_name_plural': 'Resource creation results',
            },
        ),
    ]
