# Generated by Django 5.2.17 on 2026-08-10 12:08

import privates.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('destruction', '0030_remove_destructionlist_internal_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destructionlist',
            name='destruction_report',
            field=privates.fields.PrivateMediaFileField(blank=True, null=True,
                                                        upload_to='destruction_reports/%Y/%m/%d/',
                                                        verbose_name='destruction report'),
        ),
    ]
