# Generated by Django 5.2.17 on 2026-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destruction', '0031_alter_destructionlist_destruction_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='destructionlistitem',
            name='processing_status_clarification',
            field=models.TextField(
                blank=True,
                help_text='Field used to give additional information about the status of the deletion of a destruction list item.',
                verbose_name='processing status clarification'
            ),
        ),
        migrations.AlterField(
            model_name='destructionlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
