# Generated by Django 5.2.17 on 2026-08-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destruction', '0032_destructionlistitem_processing_status_clarification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destructionlist',
            name='processing_status_clarification',
            field=models.TextField(
                blank=True,
                help_text='Field used to give additional information about the status of the deletion of a destruction list.',
                verbose_name='processing status clarification'
            ),
        ),
    ]
