version: '3.9'

services:
  keycloak-db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak-dev

  keycloak:
    depends_on:
      - keycloak-db
    container_name: keycloak_dev
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "28080:8080"
    restart: unless-stopped
    volumes:
      - ./fixtures:/opt/keycloak/data/import
    networks:
      - keycloak-dev

networks:
  keycloak-dev: