# Generated by Django 4.2.11 on 2024-06-28 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchiveConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaaktypes_short_process",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=1000),
                        default=list,
                        help_text="If a destruction list only contains cases with types present in this field, this list will have a shortened review process. This means that no archivist will have to approve this list before it is deleted.",
                        size=None,
                        verbose_name="zaaktypes short process",
                    ),
                ),
            ],
            options={
                "verbose_name": "archive configuration",
                "verbose_name_plural": "archive configurations",
            },
        ),
    ]
