# Generated by Django 4.2.14 on 2024-07-30 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveconfig",
            name="zaaktypes_short_process",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=1000),
                blank=True,
                default=list,
                help_text="If a destruction list only contains cases with types present in this field, this list will have a shortened review process. This means that no archivist will have to approve this list before it is deleted.",
                size=None,
                verbose_name="zaaktypes short process",
            ),
        ),
    ]
