# Generated by Django 4.2.15 on 2024-09-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0020_service_timeout"),
        ("config", "0002_alter_archiveconfig_zaaktypes_short_process"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selectielijst_api_service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which service to use to query the Selectielijst API.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zgw_consumers.service",
                        verbose_name="selectielijst API service",
                    ),
                ),
            ],
            options={
                "verbose_name": "API configuration",
                "verbose_name_plural": "API configurations",
            },
        ),
    ]
