# Generated by Django 4.2.15 on 2024-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_apiconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="bronorganisatie",
            field=models.CharField(
                blank=True,
                help_text="Source organisation RSIN",
                max_length=9,
                verbose_name="bronorganisatie",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="informatieobjecttype",
            field=models.URLField(
                blank=True,
                help_text="The document type URL to use when creating the case for the destruction list deletion.",
                max_length=1000,
                verbose_name="informatieobjecttype",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="resultaattype",
            field=models.URLField(
                blank=True,
                help_text="The result type URL to use when creating the case for the destruction list deletion.",
                max_length=1000,
                verbose_name="resultaattype",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="statustype",
            field=models.URLField(
                blank=True,
                help_text="The status type URL to use when creating the case for the destruction list deletion.",
                max_length=1000,
                verbose_name="statustype",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="zaaktype",
            field=models.URLField(
                blank=True,
                help_text="The case type URL to use when creating the case for the destruction list deletion.",
                max_length=1000,
                verbose_name="zaaktype",
            ),
        ),
    ]
