# Generated by Django 4.2.16 on 2024-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_archiveconfig_bronorganisatie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="selectielijstklasse",
            field=models.URLField(
                blank=True,
                help_text="The selectielijstklasse URL to use when creating the case for the destruction list deletion.",
                max_length=1000,
                verbose_name="selectielijstklasse",
            ),
        ),
    ]
