# Generated by Django 4.2.18 on 2025-03-11 11:18

from django.db import migrations, models


# Make sure the configuration is cleared. This is a change that we
# cannot automatically make, so we make sure that the field is cleared
# so that the health check can flag it.
def clear_zaaktype_config(apps, schema_editor):
    ArchiveConfig = apps.get_model("config", "ArchiveConfig")

    config = ArchiveConfig.objects.first()
    if not config:
        return

    config.zaaktype = ""
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_alter_archiveconfig_zaaktypes_short_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveconfig",
            name="zaaktype",
            field=models.CharField(
                blank=True,
                help_text="The identificatie of the zaaktype to use when creating the case for the destruction list deletion.",
                max_length=1000,
                verbose_name="zaaktype",
            ),
        ),
        migrations.RunPython(clear_zaaktype_config, clear_zaaktype_config),
    ]
