# Generated by Django 4.2.27 on 2025-12-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_remove_archiveconfig_selectielijstklasse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveconfig',
            name='zaaktype',
            field=models.URLField(blank=True, help_text='The URL of the zaaktype to use when creating the case for the destruction list deletion.', max_length=1000, verbose_name='zaaktype'),
        ),
    ]
