# Generated by Django 4.2.26 on 2025-12-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRegisterConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Identifier that used as a reference from the plugin.",
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether the plugin is enabled.",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Services needed to talk to the external register instances.",
                        to="zgw_consumers.service",
                        verbose_name="services",
                    ),
                ),
            ],
            options={
                "verbose_name": "External register plugin configuration",
                "verbose_name_plural": "External register plugin configurations",
            },
        ),
    ]
